#!/usr/bin/env python3
"""TTF -> Adafruit GFXfont header (1-bit, FreeType monochrome hinting).

  python3 ttf2gfx.py DejaVuSansMono.ttf 12 einkui_web_body > einkui_web_body.h

Characters 0x20..0xFF (Latin-1: the UI maps UTF-8 umlauts etc. to these).
Needs Pillow.
"""
import sys
from PIL import ImageFont

def main():
    path, size, name = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    bitmaps, glyphs = [], []
    for code in range(0x20, 0x100):
        ch = chr(code)
        adv = int(round(font.getlength(ch)))
        if 0x7F <= code < 0xA0:          # control characters
            glyphs.append((len(bitmaps), 0, 0, adv, 0, 0, code)); continue
        mask, (ox, oy) = font.getmask2(ch, mode="1")
        w, h = mask.size
        if w == 0 or h == 0:
            glyphs.append((len(bitmaps), 0, 0, adv, 0, 0, code)); continue
        bits = [1 if mask.getpixel((x, y)) else 0 for y in range(h) for x in range(w)]
        # trim empty rows / columns (getmask2 may pad)
        rows = [bits[y*w:(y+1)*w] for y in range(h)]
        while rows and not any(rows[0]): rows.pop(0); oy += 1
        while rows and not any(rows[-1]): rows.pop()
        if not rows:
            glyphs.append((len(bitmaps), 0, 0, adv, 0, 0, code)); continue
        left = min(r.index(1) for r in rows if 1 in r)
        right = max(len(r) - 1 - r[::-1].index(1) for r in rows if 1 in r)
        rows = [r[left:right+1] for r in rows]
        ox += left
        w, h = right - left + 1, len(rows)
        flat = [b for r in rows for b in r]
        off = len(bitmaps)
        for i in range(0, len(flat), 8):
            chunk = flat[i:i+8] + [0] * (8 - len(flat[i:i+8]))
            bitmaps.append(sum(b << (7 - j) for j, b in enumerate(chunk)))
        glyphs.append((off, w, h, adv, ox, oy - ascent, code))
    ya = ascent + descent
    out = [f"// {name}: generated by tools/ttf2gfx.py from {path.split('/')[-1]} {size}px",
           "#pragma once", "",
           f"const uint8_t {name}_bitmaps[] = {{"]
    for i in range(0, len(bitmaps), 12):
        out.append("  " + ", ".join(f"0x{b:02X}" for b in bitmaps[i:i+12]) + ",")
    out.append("};\n")
    out.append(f"const GFXglyph {name}_glyphs[] = {{")
    for off, w, h, adv, xo, yo, code in glyphs:
        c = chr(code)
        cm = repr(c) if 0x20 <= code < 0x7F and c not in "\\'" else ""
        out.append(f"  {{ {off:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, {yo:4d} }},   // 0x{code:02X} {cm}")
    out.append("};\n")
    out.append(f"const GFXfont {name} = {{\n  (uint8_t  *){name}_bitmaps,\n  (GFXglyph *){name}_glyphs,\n  0x20, 0xFF, {ya} }};\n")
    out.append(f"// Approx. {len(bitmaps) + len(glyphs) * 7 + 7} bytes")
    print("\n".join(out))

main()
